### ISSUE TITLE
Game object should NOT call console.log

### ISSUE THREAD

**Issue by SandyGifford** [SilentCog/console-game#11]
Instead of calling `console.log`, `play` function should return a `string`.  The `NewGame` function should wrap the `play` function in an anonymous function that **then** passes the string to `console.log`.  This way the same Game object can be used in a GUI _or_ in the console.  Think of it as reverse dependency injection.

**Comment by SandyGifford** [comment]
Trying to find the button that lets me label this as an "enhancement"

**Comment by mimiflynn** [comment]
If you click on the gear next to labels to at the top of the column to the right of this comment stream, it will show you available labels.

**Comment by SandyGifford** [comment]
Console is now optional, closing issue.
