### ISSUE TITLE
Replace jQuery dependency with native functionality

### ISSUE THREAD

**Issue by mimiflynn** [SilentCog/console-game#29]

**Comment by SandyGifford** [comment]
Any reason for this?

**Comment by mimiflynn** [comment]
Its just a heavy library for such little use. It could be easily replaced with native JS.

**Comment by SandyGifford** [comment]
In addition to the element selecting, it's also being used to animate the scroll for new lines.  Nothing we couldn't write on our own, still, I guess.

**Comment by mimiflynn** [comment]
On second thought, and I know this goes against what I said about heavy libraries, I want to make it an isomorphic React component because it can be a great example for a talk I've been working on.

**Comment by SandyGifford** [comment]
Are you going to be designing your own isomorphic system?  Or do you have a module I should start reading up on?

**Comment by mimiflynn** [comment]
Rolling my own. Kinda.

 It's really just using the same code to render server side as client side so I just need to render with a react component on the server then initialize with the same code on the client. It's already working for the game selector on my branch. Almost done with the game play area. 

I can walk you through it later. It would be really helpful to discuss it with you for the talk.

**Comment by SandyGifford** [comment]
Sounds good.  I'd love to hear about it.  I'm glad to hear the switcher made the transition no problem.
