### ISSUE TITLE
Help command and other enhancement lost

### ISSUE THREAD

**Issue by mimiflynn** [SilentCog/console-game#39]
Bad merge?

Help feature last found at : https://github.com/SilentCog/console-game/blob/8eeb802df105669418cab83931dc11fe85110400/source/game-engine/local-game.js#L333

The strings file references are also gone as of the above commit.

**Comment by SandyGifford** [comment]
I don't think I finished that merge - if I did we should roll it back immediately.  Sorry I haven't been active on this, works been pretty crazy
